// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJcKXTXxANBd4wqQsnwmbwgpvLhweXs6I',
    appId: '1:906948289460:web:9dc215d03fa22c570b08e1',
    messagingSenderId: '906948289460',
    projectId: 'test4-f353a',
    authDomain: 'test4-f353a.firebaseapp.com',
    storageBucket: 'test4-f353a.firebasestorage.app',
    measurementId: 'G-NQ5MQYZ2FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn7xEAOSQCheTraUllM9tP-mZvMrj6-0k',
    appId: '1:906948289460:android:82e7f0fb5539a7530b08e1',
    messagingSenderId: '906948289460',
    projectId: 'test4-f353a',
    storageBucket: 'test4-f353a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_a05qOG_1SxCcYu7MXY1LzIom4v4aJkg',
    appId: '1:906948289460:ios:d192b0c1d0575a070b08e1',
    messagingSenderId: '906948289460',
    projectId: 'test4-f353a',
    storageBucket: 'test4-f353a.firebasestorage.app',
    iosBundleId: 'com.example.myproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_a05qOG_1SxCcYu7MXY1LzIom4v4aJkg',
    appId: '1:906948289460:ios:d192b0c1d0575a070b08e1',
    messagingSenderId: '906948289460',
    projectId: 'test4-f353a',
    storageBucket: 'test4-f353a.firebasestorage.app',
    iosBundleId: 'com.example.myproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJcKXTXxANBd4wqQsnwmbwgpvLhweXs6I',
    appId: '1:906948289460:web:7e1fd51055b045bc0b08e1',
    messagingSenderId: '906948289460',
    projectId: 'test4-f353a',
    authDomain: 'test4-f353a.firebaseapp.com',
    storageBucket: 'test4-f353a.firebasestorage.app',
    measurementId: 'G-M0QXKCV14Y',
  );
}
